Check mktemp exit status

diff --git a/youtube-dl-parallel b/youtube-dl-parallel
--- a/youtube-dl-parallel
+++ b/youtube-dl-parallel
@@ -5,7 +5,13 @@ declare -a URLS URL_TITLES
 JOBS=3
 YOUTUBE_DL_ARGS=
 TITLE_PADDING=0
-TITLES_DIRECTORY=$(mktemp -d -t youtube-dl-parallel.XXX)
+
+function error() {
+    echo "Error: $@"
+    exit 1
+}
+
+TITLES_DIRECTORY=$(mktemp -d -t youtube-dl-parallel.XXX) || error "mktemp failed"
 trap 'rm -r "$TITLES_DIRECTORY"' EXIT
 
 function prefix_output() {
@@ -43,7 +49,7 @@ function parse_options()  {
             j)
                 JOBS="$OPTARG";;
             \?)
-                exit 1;;
+                error "Unknown option";;
         esac
     done
     shift $((OPTIND - 1))
@@ -80,8 +86,7 @@ function find_longest_title() {
 parse_options "$@"
 
 if test -z "$URLS"; then
-    echo "No urls specified. Try $0 -h for more information."
-    exit 1
+    error "No urls specified. Try $0 -h for more information."
 fi
 
 # Export functions and variables for use with parallel
